### ISSUE TITLE
which douglas_peucker algorithm ?

### ISSUE THREAD

**Issue by QAbot-zh** [brenhertel/TLFSD#1]
hello, I try to run your code, and I find that "no module name douglas_peucker". I find that some python versions about dp algorithm implement, so which version do you use? Can you upload your dp algorithm version ?

**Comment by brenhertel** [comment]
Sorry about that, it seems that I was missing a few files. The repository has been updated with missing files, including the filing implementing the Douglas-Peucker algorithm.
